//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagemetPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAccount
    {
        public int id { get; set; }
        public string username { get; set; }
        public string passwordHash { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string ContactNr { get; set; }
        public string Location { get; set; }
    }
}
